name: Increment version tag
on:
  schedule:
    - cron: 0 0 * * 6
  workflow_dispatch:
jobs:
  patch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get the latest tag
        id: latest-tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          dry_run: "true"
          github_token: "${{ secrets.GITHUB_TOKEN }}"
      - id: head-commit
        run: |
          set -x
          delimiter="$(openssl rand -hex 8)"
          echo "message<<$delimiter" >> "$GITHUB_OUTPUT"
          echo "$(git show --no-patch --format=%B)" >> "$GITHUB_OUTPUT"
          echo "$delimiter" >> "$GITHUB_OUTPUT"
          echo "commits=$(git rev-list ${{ steps.latest-tag.outputs.previous_tag }}..HEAD --count)" >> "$GITHUB_OUTPUT"
      - name: Bump version and push tag
        if: contains(steps.head-commit.outputs.message, '[update:patch]') && steps.head-commit.outputs.commits != '0'
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: "${{ secrets.GH_PAT }}"
